name: py
on:
      schedule:
            - cron: "*/5  * * * *" #runs at 00:00 UTC everyday
jobs:
      build:
        runs-on: ubuntu-latest
        
        steps:
          - name: actualizar sismos
            uses: actions/checkout@v2 # checkout the repository content to github runner.
          - name: setup python
            uses: actions/setup-python@v2
            with:
              persist-credentials: false 
              fetch-depth: 0
         # Python 3.7
          - name: Inicializando Python 3.7
            uses: actions/setup-python@v1
            with:
               python-version: 3.7
          - name: Install dependencies
            run: |
             python -m pip install --upgrade pip
             pip install flake8 pytest
             if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          - name: Lint with flake8
            run: |
             python temblores.py
             
              # Push a main
          - name: Pull main
            run: |
             git config --local user.email "bruno.oviedo89@gmail.com"
             git config --local user.name "brunooviedo"
             git add -A
             git commit -m "update data.csv"
             git push
             
          #- name: commit
            #run: |
               #git add data.csv
              # git commit -m "update data.csv"

   
          
