name: py
on:
      schedule:
            - cron: "*/5  * * * *" #runs at 00:00 UTC everyday
jobs:
      build:
        runs-on: ubuntu-latest
    
        steps:
          - name: actualizar sismos
            uses: actions/checkout@master #checkout the repository content to github runner.
          - name: setup python
            uses: appleboy/scp-action@master
            with:
              persist-credentials: false 
              fetch-depth: 0
         # Python 3.7
          - name: Inicializando Python 3.7
            uses: actions/setup-python@v1
            with:
               python-version: 3.7
          - name: Install dependencies
            run: |
             python -m pip install --upgrade pip
             pip install flake8 pytest
             if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          - name: Lint with flake8
            run: |
             python temblores.py
   
          
