name: actualiza sismos

on:
  push:
    branches:
    - main
    
  schedule:
  - cron: "*/10 * * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Instalando dependencias de Python
      run: |
             pip install -r requirements.txt
   
    - name: Execute Python script
      run: |
        python temblores.py
        
    - name: Pushes output to destination repository
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'data.csv'
        destination_repo: 'brunooviedo/sismos'
        destination_folder: 'data/csv'
        user_email: 'bruno.oviedo89@gmail.com'
        user_name: 'brunooviedo'
        commit_message: 'Workflow update'
             
             
